services:
  mysql:
    image: mysql:8.0
    container_name: pipelineratp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratp_db
      MYSQL_USER: ratp_user
      MYSQL_PASSWORD: ratp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: pipelineratp-app
    ports:
      - "8501:8501"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ratp_db
      DB_USER: ratp_user
      DB_PASSWORD: ratp_password
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: 